AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
